### ISSUE TITLE
OSD option changes with jtgunsmk_20221226.rbf and jt1943_20221226.rbf

### ISSUE THREAD

**Issue by wwark** [jotego/jtgng#120]
The OSD option doesn't have a video section and user port: option disappears also.
Load Rom is present again.

Thanks

**Comment by jotego** [comment]
This is fixed in 921d7b5e but I will wait for the big JTBIN update coming soon for uploading the files.

In the meantime, you can manually install the fixed files from this zip:
[release.zip](https://github.com/jotego/jtgng/files/10502554/release.zip)
