### ISSUE TITLE
1942  game list name change

### ISSUE THREAD

**Issue by suww37** [jotego/jtgng#125]
The name of the 1942 core has been changed to "Capcom - 1942". Can you tell why this game has only been turned into a “Capcom” name in front of it?

**Comment by jotego** [comment]
I think that change is not related to me. Maybe some local configuration on your MiSTer has caused it. The files names that I provide are:

```
./_alternatives/_1942/1942 (First Version).mra
./_alternatives/_1942/Supercharger 1942.mra
./_alternatives/_1942/1942 (Revision A).mra
./_alternatives/_1942/1942 (Williams Electronics license).mra
./1942 (Revision B).mra
```
