### ISSUE TITLE
Gun Smoke - Flip doesn't work

### ISSUE THREAD

**Issue by Toryalai1** [jotego/jtgng#186]
Hi Jotego,
Flip option in Gun.Smoke doesn't work. See the video below.

https://user-images.githubusercontent.com/82502378/219306911-0b885d17-da08-4aa0-b015-308d7132cfc2.mov

Information from misterfpga.org mentions the following: https://misterfpga.org/viewtopic.php?f=25&t=6158&sid=b74502c2819e7d0ccf5ff420ee3d3094

![image](https://user-images.githubusercontent.com/82502378/219307093-57d24bab-a560-4e36-bda3-bff0299bf8b3.png)

**Comment by jotego** [comment]
Thanks for reporting it.
Flip is ignored when rotation is enabled. That part is ok.
But the game should look right, not upside down.
I'm preparing the update for these and other things. I am not sure whether I'll push it tomorrow or next Friday but this is already fixed so I'm closing it here. Please give me a few days to push the update.
