### ISSUE TITLE
Gun.smoke - Top screen seems not ok in some part of the game

### ISSUE THREAD

**Issue by wwark** [jotego/jtgng#85]
Hi,
I'm using build v52ea449f
you can see screenshots below
coin screen top screen is black
![20220514_230758-screen](https://user-images.githubusercontent.com/469461/168448231-1566f1a1-c2b6-40fc-8f0e-2b37e22e880b.png)
Before enter game, top screen is not good
![20220514_225525-screen](https://user-images.githubusercontent.com/469461/168448254-b9743fff-25b8-4847-8189-ef6b406a68c1.png)

Thanks,

**Comment by jotego** [comment]
- [X] Fix (44e2170f)
- [ ] Publish

**Comment by wwark** [comment]
Thank you !
